GET http://localhost:4000/buku/

###

GET http://localhost:4000/buku/search?query=react

###

GET http://localhost:4000/buku/1

###
POST http://localhost:4000/buku/
Content-Type: application/json

{
    "judul": "Belajar React 5",
    "penerbit": "PT Maju Jaya",
    "penulis": "Riqi",
    "Keterangan": "Belajar react lebih mudah dengan membaca buku ini",
    "stok": 20,
    "harga": 100000,
    "gambar": "https://via.placeholder.com/640x480.png/002244?text=Buku+ipsa"
}

###
PATCH  http://localhost:4000/buku/10
Content-Type: application/json

{
    "keterangan": "Buku untuk belajar react"
}

###
DELETE http://localhost:4000/buku/27

###
GET http://localhost:4000/user/

###
GET http://localhost:4000/user/2

###
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "roles": ["admin"]
}

###
GET http://localhost:4000/api/test/all

###
GET http://localhost:4000/api/test/user

###
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
    "username": "Riqi",
    "password": "12345678"
}

###
GET http://localhost:4000/api/test/user
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU0NDkzNzUwLCJleHAiOjE2NTQ1ODAxNTB9.QlLhVA1HfrYiyzi8kBug59n-FS75aQtKML7a7XBBHQY

###
GET http://localhost:4000/transaksi/

###
GET http://localhost:4000/transaksi/user/Riqi

###
GET http://localhost:4000/transaksi/7

###
POST http://localhost:4000/transaksi/
Content-Type: application/json

{
    "username": "Riqi",
    "idBuku": 3,
    "jumlah": 1,
    "total": 300000,
    "status": "proses"
}

###
PATCH  http://localhost:4000/transaksi/3
Content-Type: application/json

{
    "status": "dikirim"
}

###
DELETE http://localhost:4000/transaksi/3