GET http://localhost:4000/

###

GET http://localhost:4000/search?query=react

###

GET http://localhost:4000/4

###
POST http://localhost:4000/
Content-Type: application/json

{
    "judul": "Belajar React 2",
    "penerbit": "PT Maju Jaya",
    "penulis": "Riqi",
    "Keterangan": "Belajar react lebih mudah dengan membaca buku ini",
    "stok": 20,
    "harga": 100000,
    "gambar": "https://via.placeholder.com/640x480.png/002244?text=Buku+ipsa"
}

###
PATCH  http://localhost:4000/10
Content-Type: application/json

{
    "keterangan": "Buku untuk belajar react"
}

###
DELETE http://localhost:4000/5

###
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "roles": ["admin"]
}

###
GET http://localhost:4000/api/test/all

###
GET http://localhost:4000/api/test/user

###
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
    "username": "Riqi",
    "password": "12345678"
}

###
GET http://localhost:4000/api/test/user
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU0NDkzNzUwLCJleHAiOjE2NTQ1ODAxNTB9.QlLhVA1HfrYiyzi8kBug59n-FS75aQtKML7a7XBBHQY